### PR TITLE
[Project] Added downloading of openjfx on mvn package

### PR DESCRIPTION
**Pull request by eitch**
This adds support for downloading and preparing openjfx on Windows and Linux. Windows needs to be testee

### CODE REVIEW

**Comment by eitch** [comment]
This PR will require changes to the documentation on the web page

**Comment by eitch** [comment]
This PR will require changes to the documentation on the web page

https://pi4j.com/getting-started/user-interface-with-javafx/

**Comment by FDelporte** [comment]
Oh wow! I had this on my TODO list but this is way better than I would ever be able to create. Thanks!!!

Can you add some info on how to use in the README? I will then use it to adjust the webpage...

**Review by FDelporte — APPROVED** [review]

**Comment by eitch** [comment]
Actually nothing is required, as everything is added to the distribution directory when running `mvn clean package`

**Comment by eitch** [comment]
The readme talks about gradle, but there is no gradle support in the project. Should we remove that? Furthermore i remove the link to https://pi4j.com/getting-started/user-interface-with-javafx/ as this shouldn't be needed now anymore. That would be the goal of this PR.

**Comment by FDelporte** [comment]
> The readme talks about gradle, but there is no gradle support in the project. Should we remove that? 

This is probably a left-over from copying this from minimal-example project... So yes, Gradle should be removed.

**Comment by eitch** [comment]
@FDelporte i tested it now on a Raspberry Pi 5, this lead to some additional changes, but it works nicely. I also added an assembly for a zip file and extended the Readme for this

**Comment by eitch** [comment]
Merge?

**Comment by FDelporte** [comment]
Yes merged! Sorry @eitch, forgot this one... Is there some kind of clear overview on GitHub to see pending merge requests and tickets?

**Comment by eitch** [comment]
@FDelporte not that i know of. Just realized we need this same PR for the pi4j-example-javafx project

**Pull request merged**
